# Generated by Django 5.1 on 2024-09-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(related_name='newspaper', to=settings.AUTH_USER_MODEL),
        ),
    ]
