# Generated by Django 5.1.1 on 2024-09-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_alter_newspaper_publishers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper', to='newspaper.topic'),
        ),
    ]
