# Generated by Django 5.1 on 2024-10-26 17:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_alter_newspaper_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='newspaper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
