# Generated by Django 5.1.1 on 2024-11-01 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0006_alter_newspaper_published_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                blank=True, related_name="newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newspapers",
                to="newspaper.topic",
            ),
        ),
    ]
