# Generated by Django 5.1 on 2024-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0007_alter_newspaper_publishers_alter_newspaper_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ("username",),
            },
        ),
    ]
