# Generated by Django 5.1 on 2024-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0008_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.AddField(
            model_name="redactor",
            name="is_redactor",
            field=models.BooleanField(default=False),
        ),
    ]
